-- Prontus Vitalis | 04_consultas_decisao.sql

-- Top 20 IPA
SELECT NO_MUNICIPIO, SG_UF, COMPONENTE_INTERNACOES, COMPONENTE_PERMANENCIA,
       COMPONENTE_PRESSAO_UNIDADE, INDICE_PRESSAO, CLASSIFICACAO_PRESSAO
FROM VW_IPA_FINAL ORDER BY INDICE_PRESSAO DESC FETCH FIRST 20 ROWS ONLY;

-- Distribuição das classificações
SELECT CLASSIFICACAO_PRESSAO, COUNT(*) AS MUNICIPIOS
FROM VW_IPA_FINAL GROUP BY CLASSIFICACAO_PRESSAO ORDER BY MUNICIPIOS DESC;

-- Municípios com maior IPA
SELECT COD_MUNICIPIO, NO_MUNICIPIO, SG_UF, REGIAO_DE_SAUDE, INTERNACOES,
       DIAS_PERMANENCIA, ESTABELECIMENTOS_HOSPITALARES,
       ROUND(INDICE_PRESSAO, 2) AS IPA, CLASSIFICACAO_PRESSAO
FROM VW_IPA_FINAL ORDER BY INDICE_PRESSAO DESC FETCH FIRST 15 ROWS ONLY;

-- Municípios críticos ou altos
SELECT COD_MUNICIPIO, NO_MUNICIPIO, SG_UF, REGIAO_DE_SAUDE, INTERNACOES,
       DIAS_PERMANENCIA, ESTABELECIMENTOS_HOSPITALARES,
       COMPONENTE_INTERNACOES, COMPONENTE_PERMANENCIA,
       COMPONENTE_PRESSAO_UNIDADE, INDICE_PRESSAO, CLASSIFICACAO_PRESSAO
FROM VW_IPA_FINAL
WHERE CLASSIFICACAO_PRESSAO IN ('Crítica', 'Alta')
ORDER BY INDICE_PRESSAO DESC;

-- Maior demanda por hospital
SELECT COD_MUNICIPIO, NO_MUNICIPIO, SG_UF, REGIAO_DE_SAUDE, INTERNACOES,
       ESTABELECIMENTOS_HOSPITALARES,
       ROUND(INTERNACOES / NULLIF(ESTABELECIMENTOS_HOSPITALARES, 0), 2)
       AS INTERNACOES_POR_HOSPITAL, INDICE_PRESSAO, CLASSIFICACAO_PRESSAO
FROM VW_IPA_FINAL
WHERE ESTABELECIMENTOS_HOSPITALARES > 0
ORDER BY INTERNACOES_POR_HOSPITAL DESC FETCH FIRST 15 ROWS ONLY;

-- Maior mortalidade
SELECT COD_MUNICIPIO, NO_MUNICIPIO, SG_UF, REGIAO_DE_SAUDE, INTERNACOES,
       OBITOS, ROUND(OBITOS / NULLIF(INTERNACOES, 0) * 100, 2)
       AS TAXA_MORTALIDADE, INDICE_PRESSAO, CLASSIFICACAO_PRESSAO
FROM VW_IPA_FINAL WHERE INTERNACOES > 0
ORDER BY TAXA_MORTALIDADE DESC FETCH FIRST 15 ROWS ONLY;

-- Resumo regional
SELECT REGIAO_DE_SAUDE, MACRORREGIAO_DE_SAUDE, SG_UF, COUNT(*) AS MUNICIPIOS,
       SUM(INTERNACOES) AS INTERNACOES, SUM(OBITOS) AS OBITOS,
       SUM(DIAS_PERMANENCIA) AS DIAS_PERMANENCIA,
       SUM(ESTABELECIMENTOS_HOSPITALARES) AS ESTABELECIMENTOS_HOSPITALARES,
       ROUND(AVG(INDICE_PRESSAO), 2) AS IPA_MEDIO
FROM VW_IPA_FINAL
GROUP BY REGIAO_DE_SAUDE, MACRORREGIAO_DE_SAUDE, SG_UF
ORDER BY INTERNACOES DESC FETCH FIRST 15 ROWS ONLY;

-- Evolução mensal
SELECT PERIODO, PERIODO_DATA, MUNICIPIOS, INTERNACOES, OBITOS,
       DIAS_PERMANENCIA, VALOR_TOTAL, MEDIA_PERMANENCIA_MEDIA,
       TAXA_MORTALIDADE_MEDIA
FROM VW_RESUMO_MENSAL ORDER BY PERIODO_DATA;

-- Top 10 IPA
SELECT NO_MUNICIPIO AS MUNICIPIO, SG_UF AS UF, REGIAO_DE_SAUDE,
       INTERNACOES, DIAS_PERMANENCIA, ESTABELECIMENTOS_HOSPITALARES,
       ROUND(INDICE_PRESSAO, 2) AS IPA, CLASSIFICACAO_PRESSAO
FROM VW_IPA_FINAL ORDER BY INDICE_PRESSAO DESC FETCH FIRST 10 ROWS ONLY;
