-- Prontus Vitalis | 02_views_integracao.sql

CREATE OR REPLACE VIEW VW_PRONTUS_VITALIS AS
SELECT
    s.MUNICIPIO, SUBSTR(s.MUNICIPIO, 1, 6) AS COD_MUNICIPIO,
    f.NO_MUNICIPIO, f.SG_UF, f.UF, f.MACRORREGIAO_DE_SAUDE,
    f.REGIAO_DE_SAUDE, f.POPULACAO_IBGE_2022, s.PERIODO, s.PERIODO_DATA,
    s.INTERNACOES, s.OBITOS, s.DIAS_PERMANENCIA, s.MEDIA_PERMANENCIA,
    s.TAXA_MORTALIDADE, s.VALOR_TOTAL, c.TOTAL_ESTABELECIMENTOS,
    c.ESTABELECIMENTOS_HOSPITALARES, c.ESTABELECIMENTOS_SUS,
    c.LATITUDE_MEDIA, c.LONGITUDE_MEDIA,
    CASE WHEN c.ESTABELECIMENTOS_HOSPITALARES > 0
         THEN ROUND(s.INTERNACOES / c.ESTABELECIMENTOS_HOSPITALARES, 2)
         ELSE 0 END AS INTERNACOES_POR_HOSPITAL
FROM SIH_SUS_CONSOLIDADO s
LEFT JOIN CNES_MUNICIPAL c ON SUBSTR(s.MUNICIPIO, 1, 6) = c.COD_MUNICIPIO
LEFT JOIN FONTE_3_REGIOES f ON SUBSTR(s.MUNICIPIO, 1, 6) = f.COD_MUNICIPIO;

CREATE OR REPLACE VIEW VW_IPA_MUNICIPAL AS
SELECT
    COD_MUNICIPIO, NO_MUNICIPIO, SG_UF, UF, MACRORREGIAO_DE_SAUDE,
    REGIAO_DE_SAUDE, POPULACAO_IBGE_2022, SUM(INTERNACOES) AS INTERNACOES,
    SUM(OBITOS) AS OBITOS, SUM(DIAS_PERMANENCIA) AS DIAS_PERMANENCIA,
    SUM(VALOR_TOTAL) AS VALOR_TOTAL, AVG(MEDIA_PERMANENCIA) AS MEDIA_PERMANENCIA,
    AVG(TAXA_MORTALIDADE) AS TAXA_MORTALIDADE,
    MAX(TOTAL_ESTABELECIMENTOS) AS TOTAL_ESTABELECIMENTOS,
    MAX(ESTABELECIMENTOS_HOSPITALARES) AS ESTABELECIMENTOS_HOSPITALARES,
    MAX(ESTABELECIMENTOS_SUS) AS ESTABELECIMENTOS_SUS
FROM VW_PRONTUS_VITALIS
GROUP BY COD_MUNICIPIO, NO_MUNICIPIO, SG_UF, UF,
         MACRORREGIAO_DE_SAUDE, REGIAO_DE_SAUDE, POPULACAO_IBGE_2022;

CREATE OR REPLACE VIEW VW_RESUMO_REGIAO AS
SELECT
    REGIAO_DE_SAUDE, MACRORREGIAO_DE_SAUDE, SG_UF,
    COUNT(DISTINCT COD_MUNICIPIO) AS MUNICIPIOS,
    SUM(INTERNACOES) AS INTERNACOES, SUM(OBITOS) AS OBITOS,
    SUM(DIAS_PERMANENCIA) AS DIAS_PERMANENCIA, SUM(VALOR_TOTAL) AS VALOR_TOTAL,
    ROUND(AVG(TAXA_MORTALIDADE), 2) AS TAXA_MORTALIDADE_MEDIA,
    SUM(ESTABELECIMENTOS_HOSPITALARES) AS ESTABELECIMENTOS_HOSPITALARES
FROM VW_IPA_MUNICIPAL
GROUP BY REGIAO_DE_SAUDE, MACRORREGIAO_DE_SAUDE, SG_UF;

CREATE OR REPLACE VIEW VW_RESUMO_MENSAL AS
SELECT
    PERIODO, PERIODO_DATA, COUNT(DISTINCT COD_MUNICIPIO) AS MUNICIPIOS,
    SUM(INTERNACOES) AS INTERNACOES, SUM(OBITOS) AS OBITOS,
    SUM(DIAS_PERMANENCIA) AS DIAS_PERMANENCIA, SUM(VALOR_TOTAL) AS VALOR_TOTAL,
    ROUND(AVG(MEDIA_PERMANENCIA), 2) AS MEDIA_PERMANENCIA_MEDIA,
    ROUND(AVG(TAXA_MORTALIDADE), 2) AS TAXA_MORTALIDADE_MEDIA
FROM VW_PRONTUS_VITALIS
GROUP BY PERIODO, PERIODO_DATA;
