-- Prontus Vitalis | 03_views_ipa.sql

CREATE OR REPLACE VIEW VW_IPA_MAXIMOS AS
SELECT
    MAX(INTERNACOES) AS MAX_INTERNACOES,
    MAX(DIAS_PERMANENCIA) AS MAX_DIAS_PERMANENCIA,
    MAX(CASE WHEN ESTABELECIMENTOS_HOSPITALARES > 0
             THEN INTERNACOES / ESTABELECIMENTOS_HOSPITALARES ELSE 0 END)
             AS MAX_INTERNACOES_POR_HOSPITAL
FROM VW_IPA_MUNICIPAL;

CREATE OR REPLACE VIEW VW_IPA_COMPONENTES AS
SELECT
    m.COD_MUNICIPIO, m.NO_MUNICIPIO, m.SG_UF, m.UF,
    m.MACRORREGIAO_DE_SAUDE, m.REGIAO_DE_SAUDE, m.POPULACAO_IBGE_2022,
    m.INTERNACOES, m.OBITOS, m.DIAS_PERMANENCIA, m.VALOR_TOTAL,
    m.TOTAL_ESTABELECIMENTOS, m.ESTABELECIMENTOS_HOSPITALARES,
    m.ESTABELECIMENTOS_SUS,
    ROUND(m.INTERNACOES / (SELECT MAX_INTERNACOES FROM VW_IPA_MAXIMOS) * 100, 2)
        AS COMPONENTE_INTERNACOES,
    ROUND(m.DIAS_PERMANENCIA / (SELECT MAX_DIAS_PERMANENCIA FROM VW_IPA_MAXIMOS) * 100, 2)
        AS COMPONENTE_PERMANENCIA,
    CASE WHEN m.ESTABELECIMENTOS_HOSPITALARES > 0 THEN
        ROUND(
            (m.INTERNACOES / m.ESTABELECIMENTOS_HOSPITALARES) /
            (SELECT MAX_INTERNACOES_POR_HOSPITAL FROM VW_IPA_MAXIMOS) * 100, 2
        )
    ELSE 0 END AS COMPONENTE_PRESSAO_UNIDADE
FROM VW_IPA_MUNICIPAL m;

CREATE OR REPLACE VIEW VW_IPA_FINAL AS
SELECT
    COD_MUNICIPIO, NO_MUNICIPIO, SG_UF, UF, MACRORREGIAO_DE_SAUDE,
    REGIAO_DE_SAUDE, POPULACAO_IBGE_2022, INTERNACOES, OBITOS,
    DIAS_PERMANENCIA, VALOR_TOTAL, TOTAL_ESTABELECIMENTOS,
    ESTABELECIMENTOS_HOSPITALARES, ESTABELECIMENTOS_SUS,
    COMPONENTE_INTERNACOES, COMPONENTE_PERMANENCIA, COMPONENTE_PRESSAO_UNIDADE,
    ROUND(COMPONENTE_INTERNACOES * 0.40 +
          COMPONENTE_PERMANENCIA * 0.30 +
          COMPONENTE_PRESSAO_UNIDADE * 0.30, 2) AS INDICE_PRESSAO,
    CASE
        WHEN COMPONENTE_INTERNACOES * 0.40 + COMPONENTE_PERMANENCIA * 0.30
             + COMPONENTE_PRESSAO_UNIDADE * 0.30 >= 75 THEN 'Crítica'
        WHEN COMPONENTE_INTERNACOES * 0.40 + COMPONENTE_PERMANENCIA * 0.30
             + COMPONENTE_PRESSAO_UNIDADE * 0.30 >= 50 THEN 'Alta'
        WHEN COMPONENTE_INTERNACOES * 0.40 + COMPONENTE_PERMANENCIA * 0.30
             + COMPONENTE_PRESSAO_UNIDADE * 0.30 >= 25 THEN 'Moderada'
        ELSE 'Baixa'
    END AS CLASSIFICACAO_PRESSAO
FROM VW_IPA_COMPONENTES;
